import {
  Activity,
  Bike,
  Dices,
  Dumbbell,
  Flame,
  Flower2,
  Footprints,
  Gamepad2,
  Goal,
  HeartPulse,
  Mountain,
  Music,
  PersonStanding,
  Sailboat,
  Sparkles,
  Swords,
  Target,
  Trophy,
  Volleyball,
  Waves,
  Wind,
  type LucideIcon,
} from 'lucide-react';

// Ícone de traço por modalidade (categories.slug), no lugar dos emojis
const ICONS: Record<string, LucideIcon> = {
  funcional: Activity,
  musculacao: Dumbbell,
  crossfit: Flame,
  hiit: Flame,
  calistenia: PersonStanding,
  lutas: Swords,
  boxe: Swords,
  'muay-thai': Swords,
  'jiu-jitsu': Swords,
  yoga: Flower2,
  pilates: Flower2,
  meditacao: Wind,
  alongamento: PersonStanding,
  'beach-tennis': Trophy,
  tenis: Trophy,
  padel: Trophy,
  futevolei: Volleyball,
  'volei-praia': Volleyball,
  surf: Waves,
  sup: Sailboat,
  natacao: Waves,
  futebol: Goal,
  futsal: Goal,
  handebol: Goal,
  basquete: Goal,
  corrida: Footprints,
  'trilha-caminhada': Mountain,
  ciclismo: Bike,
  skate: Activity,
  airsoft: Target,
  paintball: Target,
  danca: Music,
  'jogos-tabuleiro': Dices,
  esports: Gamepad2,
  'fisioterapia-esportiva': HeartPulse,
  'reabilitacao-postural': HeartPulse,
  'rpg-fisio': HeartPulse,
};

export const sportIcon = (slug: string | null | undefined): LucideIcon => (slug && ICONS[slug]) || Sparkles;
